Snapshot bootstrap phase changes
yugabyte/debezium-connector-yugabytedb pull request #141
Opened 2023-01-05 05:31 UTC by vaibhav-yb

This PR includes these changes:
1. Before starting the snapshot, set the checkpoint with `0,0` instead of `-1,-1`
2. For confirming whether the snapshot is completed, only check for the `key`, `write_id` and `snapshotTime`
3. The first GetChanges call to request the snapshot has the `snapshotTime` set to 0

2023-01-05 05:40 UTC, suranjan requested changes

2023-01-05 05:40 UTC, suranjan commented on src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
> +                if (Arrays.equals(finalOpId.getKey(), "".getBytes())
convert to a better name function

2023-01-05 05:40 UTC, suranjan commented on src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
> +      return sourceInfo.lsn() == null ? new OpId(-1, -1, "".getBytes(), -1, 0)
Comment the significance of OpId(-1, -1, "".getBytes(), -1, 0)

2023-01-13 06:32 UTC, vrajat commented
re: the test - what was the symptom? Was snapshot missing rows?

2023-01-13 06:39 UTC, vaibhav-yb commented
> re: the test - what was the symptom before the fix? Was snapshot missing rows?

Yes, there was some data loss with snapshot, specifically around the transition from snapshot to streaming. @adithya-yb will be able to provide more details.

2023-01-19 04:57 UTC, adithya-yb approved these changes

2023-01-19 07:27 UTC, merged