Changes to add configurable rpc retry attempts
yugabyte/debezium-connector-yugabytedb pull request #277
Opened 2023-10-06 11:45 UTC by Sumukh-Phalgaonkar

Currently, the AsynClient retries an RPC for 100 times within an interval of almost one minute. This results in `Too many attempts` exception much before the specified time out is reached. 

This PR contains changes to add configurable maximum number of rpc retry attempts, while creating `AsyncClient`. The default number of retries have been set to a sufficiently large number, such that all the attempts will not get over much before the specified timeout.

2023-10-06 12:00 UTC, vaibhav-yb requested changes

2023-10-06 12:00 UTC, vaibhav-yb commented on pom.xml
> +        <version.ybclient>0.8.65-SNAPSHOT</version.ybclient>
YBClient service is already on `0.8.66` - make sure you increase your version accordingly.

2023-10-06 12:00 UTC, vaibhav-yb commented on src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
> +                                     int maxNumTablets, String certFile, String clientCert, String clientKey, int maxAttempts) {
If I remember correctly, this method is just used in `YugabyteDBConnector` - we can remove this method now and use the one in `YBClientUtils` as the later one only takes connector configuration as a parameter. We can then use the later method everywhere.

2023-10-10 07:10 UTC, suranjan approved these changes

2023-10-11 05:27 UTC, vaibhav-yb approved these changes

2023-10-11 06:30 UTC, merged