Shift tablet removal from shouldWaitForCallback set logic to snapshot consumption phase
yugabyte/debezium-connector-yugabytedb pull request #302
Opened 2023-12-05 18:34 UTC by siddharth2411

2023-12-07 10:07 UTC, suranjan requested changes

2023-12-07 10:07 UTC, suranjan commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
> +        YugabyteDBSnapshotChangeEventSource.FAIL_AFTER_SETTING_INITIAL_CHECKPOINT = false;
Don't see any specific test for this?

2023-12-07 10:39 UTC, siddharth2411 commented
Some open questions:

1. Currently, we add all the tablets to the `shouldWaitForCallback` set including the ones on which we the user has not asked us to take snapshot ([code](https://github.com/yugabyte/debezium-connector-yugabytedb/blob/0382188d7479f1f6d7812922250f50e50827346a/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java#L455C9-L455C46)). So, Should we shift the limit of addition of tablets to this set to only tablets meant for snapshot?

2. Also, once we mark snapshot done on service for a tablet, should we remove the tablet's entry from this set if its present? (after this [line](https://github.com/yugabyte/debezium-connector-yugabytedb/blob/0382188d7479f1f6d7812922250f50e50827346a/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java#L683))

2023-12-07 11:23 UTC, vaibhav-yb approved these changes
Approving with some minor changes requested.

2023-12-12 11:55 UTC, siddharth2411 commented
> Some open questions:
> 
> 1. Currently, we add all the tablets to the `shouldWaitForCallback` set including the ones on which we the user has not asked us to take snapshot ([code](https://github.com/yugabyte/debezium-connector-yugabytedb/blob/0382188d7479f1f6d7812922250f50e50827346a/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java#L455C9-L455C46)). So, Should we shift the limit of addition of tablets to this set to only tablets meant for snapshot?
> 2. Also, once we mark snapshot done on service for a tablet, should we remove the tablet's entry from this set if its present? (after this [line](https://github.com/yugabyte/debezium-connector-yugabytedb/blob/0382188d7479f1f6d7812922250f50e50827346a/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java#L683))

This things have been added as part of this PR.

2023-12-13 12:26 UTC, siddharth2411 commented
Changes in this PR were merged as part of https://github.com/yugabyte/debezium-connector-yugabytedb/pull/306. Closing this PR.

2023-12-13 12:26 UTC, closed without merging