Test improvements
yugabyte/debezium-connector-yugabytedb pull request #5
Opened 2022-06-16 20:26 UTC by vaibhav-yb

The tests in this project now work with `TestContainers` and can be simply run using `mvn test`.

2022-06-21 04:26 UTC, vrajat requested changes
Can you also paste the o/p of mvn test? Just the test results part. I am curious if the IT test runs as part of test.

2022-06-21 04:26 UTC, vrajat commented on src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
> +    // public static YugabyteDBConnection create(String host, String ysqlPort) {
Can you remove this? We can always add it later if required. Seems like a simple fn. and available in git history

2022-06-21 04:26 UTC, vrajat commented on src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
> +        /*
Delete the code. Available in history if required.

2022-06-21 04:26 UTC, vrajat commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorIT.java
> +public class YugabyteDBConnectorIT extends AbstractConnectorTest {
The class and file name has IT. Maven will consider it as an integration test. Is this different from DBCompleteTests? AFAICT, both start containers.

2022-06-21 04:26 UTC, vrajat commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
> +        Thread.sleep(3000);
Is it possible to use awaitility with a condition? https://github.com/awaitility/awaitility

2022-06-21 04:26 UTC, vrajat commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
> +        Thread.sleep(3000);
Possible to awaitility?

2022-06-21 15:07 UTC, suranjan commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
> +        Thread.sleep(3000);
Why sleep?

2022-06-21 15:08 UTC, suranjan commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
> +        Thread.sleep(3000);
why sleep?

2022-06-21 15:08 UTC, suranjan commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
> +        Thread.sleep(3000);
why sleep?

2022-06-21 15:09 UTC, suranjan commented on src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
> +        Thread.sleep(3000);
why sleep? You have used sleep liberally, this is bad practice. Also, I don't understand, can you outline why we need it here? Is the database not ready?

2022-06-23 08:08 UTC, vaibhav-yb commented
Merging now, will make the recommended changes in a new PR.

2022-06-23 08:08 UTC, merged